services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=mysql://${DATABASE_USER}:${DATABASE_PASSWORD}@database/${DATABASE_DB}
      - HOST=${HOST}
      - PORT=${PORT}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
  database:
    image: mysql/mysql-server:8.0
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_DATABASE=${DATABASE_DB}
      - MYSQL_ROOT_HOST=%
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u tournament --password=${DATABASE_PASSWORD}
      start_period: 5s
      interval: 5s
      timeout: 1s
      retries: 15
    ports:
      - 3306:3306
    volumes:
      - database-data:/var/lib/mysql

volumes:
  database-data: