services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DATABASE_URL=mongodb://${DATABASE_USER}:${DATABASE_PASSWORD}@database/
      - HOST=${HOST}
      - PORT=${PORT}
      - SECRET_KEY=${SECRET_KEY}
    depends_on:
      database:
        condition: service_healthy
    ports:
      - ${PORT}:${PORT}
  database:
    image: mongo
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_PASSWORD=${DATABASE_PASSWORD}
      - MONGO_INITDB_ROOT_USERNAME=${DATABASE_USER}
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet}
      start_period: 5s
      interval: 5s
      timeout: 1s
      retries: 15
    ports:
      - 27017:27017
    volumes:
      - database-data:/data/db

volumes:
  database-data: